### ISSUE TITLE
RPKI Validator will be descontinued

### ISSUE THREAD

**Issue by wolfwander** [OpenBMP/OpenBMP.github.io#1]
Hi!<br/>
<br/>
RPKI Validator Java application will be archived and will not receive any update or security patch on July 1st 2021 according to [their announcement](https://www.ripe.net/manage-ips-and-asns/resource-management/rpki/tools-and-resources).<br/>
Is there any plan to replace it?<br/>
<br/>
Thanks

**Comment by TimEvens** [comment]
Yes, this has been replaced by pulling data from a cache.   Instead of running a validator, which has been problematic with proxies, ... you can now define a URL where to pull the data.  The default config is below:

```
      - RPKI_URL=https://rpki.cloudflare.com/rpki.json  # define the URL to retrieve json endoed RPKI data
      - RPKI_PASS=None
      - RPKI_USER=None
      - ENABLE_RPKI=1                                   # 1 enables, 0 disables RPKI sync
      ```
      
I'll close this considering it has been replaced.
