### ISSUE TITLE
OpenBMP do not create tables after installations

### ISSUE THREAD

**Issue by kmorales026** [OpenBMP/OpenBMP.github.io#2]
Hi, I installed OpenBMP following the oficial guide, the installations works fine!, but grafana do not graphs any data., I checked container obmp-grafana and obmp-psql-app, but tables do not created on database openbmp. 

I configured the router to send data to OpenBMP machine. and session is up.

openbmp=# \c openbmp
You are now connected to database "openbmp" as user "openbmp".
openbmp=# 
openbmp=# \dt
Did not find any relations.
openbmp=#               

root@34cd38721bca:/tmp# kafka-tools -b obmp-kafka:29092 print_consumer_lag openbmp.parsed.unicast_prefix obmp-psql-consumer
 Partition    Lag    Latest Offset    Current Offset
-----------  -----  ---------------  ----------------
     7         3           2                -1
     4         5           4                -1
     0         1           0                -1
     6         3           2                -1
     2         1           0                -1
     1         1           0                -1
     3         1           0                -1
     5         1           0                -1

 Total lag: 16 messages.
root@34cd38721bca:/tmp# 

Could you help me please..

**Comment by Dmitry321** [comment]
Same problem. Tables not created. But offsets are positive digits.

**Comment by TimEvens** [comment]
@kmorales026 , can you try the latest release now?  It should resolve your issues.  I'll close this for now.
