### ISSUE TITLE
Router name

### ISSUE THREAD

**Issue by ktoczyski** [OpenBMP/OpenBMP.github.io#3]
Hello,

Is it possible to display full FQDN name or partial (name + subdomain) for routers in Grafana? Now is see only name. In my network I have a few routers with the same name but different subdomain and now I don't know which is which in Grafana filters.

**Comment by ktoczyski** [comment]
I resolved it. OpenBMP take the router name via SNMP. I change it and now is ok.

**Comment by TimEvens** [comment]
Thanks for the update.
